### ISSUE TITLE
otpless-headless-rn fails to compile on React Native 0.83 (Expo SDK 55)

### ISSUE THREAD

**Issue by vikas-kukreti** [otpless-tech/react-native-headless-sdk#22]
## Description

`otpless-headless-rn@2.0.7` fails to compile on React Native 0.83.x (Expo SDK 55) due to breaking API changes in the React Native bridge layer.

## Environment

- **otpless-headless-rn**: 2.0.7
- **react-native**: 0.83.2
- **expo**: 55.0.3
- **Kotlin**: 2.1.20
- **Gradle**: 9.0.0

## Build Error
```
> Task :otpless-headless-rn:compileDebugKotlin FAILED
e: OtplessReactNativeModule.kt:29:1 Class 'OtplessHeadlessRNModule' is not abstract and does not implement abstract members:
fun onActivityResult(activity: Activity, requestCode: Int, resultCode: Int, data: Intent?): Unit
fun onNewIntent(intent: Intent): Unit
e: OtplessReactNativeModule.kt:72:6 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:76:22 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:85:22 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:97:44 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:98:38 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:153:5 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:200:6 Unresolved reference 'currentActivity'.
e: OtplessReactNativeModule.kt:189:3 'onActivityResult' overrides nothing.
e: OtplessReactNativeModule.kt:198:3 'onNewIntent' overrides nothing.
```

## Root Cause
React Native 0.83 introduced two breaking changes in its Android bridge API:### 
1. `ActivityEventListener` method signatures changed to non-nullable parameters
2. `currentActivity` removed as a direct property on `ReactContextBaseJavaModule`

## Suggested Fix

In `OtplessReactNativeModule.kt`:

1. Replace all bare `currentActivity` references with `reactApplicationContext.currentActivity`
2. Change `onActivityResult(activity: Activity?, ...)` to `onActivityResult(activity: Activity, ...)`
3. Change `onNewIntent(intent: Intent?)` to `onNewIntent(intent: Intent)` and remove the `intent ?: return` null guard
